import os
import uuid
import io
import logging
from PIL import Image
from werkzeug.utils import secure_filename
from sqlalchemy import text
from config import Config
from database import db_session, MedicalImage
from dotenv import load_dotenv
from huggingface_hub import InferenceClient
from ..modelcaption import generate_medical_description

# Load environment variables
load_dotenv()

# Set up logging
logger = logging.getLogger(__name__)

class ImageService:
    # Hugging Face configuration
    HF_TOKEN = os.getenv("HF_TOKEN")
    IMAGE_MODEL_ID = os.getenv("HF_IMAGE_MODEL_ID", "microsoft/BiomedVLP-CXR-BERT-specialized")
    
    @staticmethod
    def allowed_file(filename):
        """Check if a file has an allowed extension"""
        return '.' in filename and \
               filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_EXTENSIONS
    
    @staticmethod
    def analyze_image(image_path):
        """Generate a diagnosis for a medical image without saving to database"""
        try:
            # First try specialized medical model
            description = generate_medical_description(image_path)
            logger.info(f"Generated medical description using specialized model")
            
            # If we didn't get a usable result, enhance it with additional analysis
            if not description or description == "No description available":
                description = ImageService._enhance_description(
                    "A medical image that requires analysis", 
                    "standard"
                )
                
            # Add standard disclaimer
            disclaimer = "\n\nNote: This analysis is generated by AI and should not replace professional medical advice."
            description = description.strip() + disclaimer
            return description
                
        except Exception as e:
            logger.error(f"Error generating diagnosis: {e}")
            return "Unable to generate a detailed diagnosis for this image. Please consult a medical professional for proper evaluation."
    
    @staticmethod
    def _enhance_description(basic_caption, analysis_type="standard"):
        """Enhance a basic caption with medical details using Hugging Face"""
        try:
            # Initialize the HF inference client
            client = InferenceClient(
                model="mistralai/Mistral-7B-Instruct-v0.2",
                token=ImageService.HF_TOKEN
            )
            
            # Create medical assessment prompt
            medical_prompt = (
                "You are a medical imaging expert. Analyze this image and provide a detailed medical "
                "assessment. The image appears to show: " + basic_caption + "\n\n"
                "Please provide a medical interpretation including possible diagnoses, "
                "abnormalities, and key observations."
            )
            
            # Get enhanced description from text model
            response = client.text_generation(
                prompt=medical_prompt,
                max_new_tokens=300,
                temperature=0.7,
                return_full_text=False
            )
            
            detailed_diagnosis = response if isinstance(response, str) else response.get("generated_text", "")
            return detailed_diagnosis.strip()
            
        except Exception as e:
            logger.error(f"Error enhancing description: {e}")
            # Fall back to basic caption
            return "Medical image analysis. Please consult a healthcare professional for proper interpretation."
    
    @staticmethod
    def save_uploaded_file(file):
        """Save an uploaded file and return its metadata"""
        if not file or not ImageService.allowed_file(file.filename):
            return None
            
        # Generate a secure filename with UUID to avoid conflicts
        original_filename = secure_filename(file.filename)
        extension = original_filename.rsplit('.', 1)[1].lower()
        unique_filename = f"{uuid.uuid4().hex}.{extension}"
        
        # Create directory if it doesn't exist
        if not os.path.exists(Config.LOCAL_STORAGE_PATH):
            os.makedirs(Config.LOCAL_STORAGE_PATH, exist_ok=True)
        
        # Save the file locally
        file_path = os.path.join(Config.LOCAL_STORAGE_PATH, unique_filename)
        with open(file_path, "wb") as buffer:
            file.file.seek(0)  # Ensure we're at the start of the file
            buffer.write(file.file.read())
        
        # Generate description using medical captioning model
        description = ImageService.analyze_image(file_path)
        
        # Create database record
        url_path = f"{Config.IMAGES_URL_BASE}{unique_filename}"
        medical_image = MedicalImage(
            filename=unique_filename,
            filepath=file_path,
            url_path=url_path,
            description=description
        )
        
        db_session.add(medical_image)
        db_session.commit()
        
        return {
            "id": medical_image.id,
            "filename": unique_filename,
            "url_path": url_path,
            "description": description
        }
    
    @staticmethod
    def get_random_image():
        """Get a random image from the database"""
        # Use text() to properly wrap the RANDOM() function
        image = db_session.query(MedicalImage).order_by(text('RANDOM()')).first()
        
        if not image:
            return None
            
        return {
            "id": image.id,
            "filename": image.filename,
            "url_path": image.url_path,
            "description": image.description
        }
    
    @staticmethod
    def get_image_by_id(image_id):
        """Get an image by its ID"""
        image = db_session.query(MedicalImage).filter_by(id=image_id).first()
        
        if not image:
            return None
            
        return {
            "id": image.id,
            "filename": image.filename,
            "url_path": image.url_path,
            "description": image.description
        }

    @staticmethod
    def regenerate_description(image_id):
        """Regenerate the description for an existing image"""
        image = db_session.query(MedicalImage).filter_by(id=image_id).first()
        
        if not image:
            return None
        
        # Generate new description using specialized medical captioning
        new_description = ImageService.analyze_image(image.filepath)
        
        # Update the database
        image.description = new_description
        db_session.commit()
        
        return {
            "id": image.id,
            "filename": image.filename,
            "url_path": image.url_path,
            "description": new_description
        } 